version: "3.6"

services:
    akhq:
      image: tchiotludo/akhq
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              docker-kafka-server:
                properties:
                  bootstrap.servers: ${BOOTSTRAP_URL}
      ports:
        - 8080:8080
